const REWARD_TIER_COMPONENTS = [
  { internalType: "uint256", name: "rewardValue", type: "uint256" },
  { internalType: "bool", name: "isRewardTier", type: "bool" },
  { internalType: "bytes32[]", name: "itemId", type: "bytes32[]" },
  { internalType: "uint256[]", name: "itemValue", type: "uint256[]" },
  { internalType: "uint256[]", name: "itemQuantity", type: "uint256[]" },
] as const;

export const ALL_OR_NOTHING_ABI = [
  { inputs: [], name: "AccessCheckerUnauthorized", type: "error" },
  { inputs: [], name: "AllOrNothingFeeNotDisbursed", type: "error" },
  { inputs: [], name: "AllOrNothingInvalidInput", type: "error" },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "AllOrNothingNotClaimable",
    type: "error",
  },
  { inputs: [], name: "AllOrNothingNotSuccessful", type: "error" },
  { inputs: [], name: "AllOrNothingRewardExists", type: "error" },
  { inputs: [], name: "AllOrNothingTransferFailed", type: "error" },
  { inputs: [], name: "AllOrNothingUnAuthorized", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "inputTime", type: "uint256" },
      { internalType: "uint256", name: "currentTime", type: "uint256" },
    ],
    name: "CurrentTimeIsGreater",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "inputTime", type: "uint256" },
      { internalType: "uint256", name: "currentTime", type: "uint256" },
    ],
    name: "CurrentTimeIsLess",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "initialTime", type: "uint256" },
      { internalType: "uint256", name: "finalTime", type: "uint256" },
    ],
    name: "CurrentTimeIsNotWithinRange",
    type: "error",
  },
  { inputs: [], name: "AllOrNothingFeeAlreadyDisbursed", type: "error" },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "AllOrNothingTokenNotAccepted",
    type: "error",
  },
  { inputs: [], name: "TreasuryCampaignInfoIsPaused", type: "error" },
  { inputs: [], name: "TreasuryFeeNotDisbursed", type: "error" },
  { inputs: [], name: "TreasurySuccessConditionNotFulfilled", type: "error" },
  { inputs: [], name: "TreasuryTransferFailed", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "token", type: "address" },
      { indexed: false, internalType: "uint256", name: "protocolShare", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "platformShare", type: "uint256" },
    ],
    name: "FeesDisbursed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "address", name: "account", type: "address" },
      { indexed: false, internalType: "bytes32", name: "message", type: "bytes32" },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "backer", type: "address" },
      { indexed: true, internalType: "address", name: "pledgeToken", type: "address" },
      { indexed: false, internalType: "bytes32", name: "reward", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "pledgeAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "shippingFee", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "tokenId", type: "uint256" },
      { indexed: false, internalType: "bytes32[]", name: "rewards", type: "bytes32[]" },
    ],
    name: "Receipt",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "tokenId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "refundAmount", type: "uint256" },
      { indexed: false, internalType: "address", name: "claimer", type: "address" },
    ],
    name: "RefundClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bytes32[]", name: "rewardNames", type: "bytes32[]" },
      {
        components: [...REWARD_TIER_COMPONENTS],
        indexed: false,
        internalType: "struct AllOrNothing.Reward[]",
        name: "rewards",
        type: "tuple[]",
      },
    ],
    name: "RewardsAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "bytes32", name: "rewardName", type: "bytes32" }],
    name: "RewardRemoved",
    type: "event",
  },
  { anonymous: false, inputs: [], name: "SuccessConditionNotFulfilled", type: "event" },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "address", name: "account", type: "address" },
      { indexed: false, internalType: "bytes32", name: "message", type: "bytes32" },
    ],
    name: "Unpaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "account", type: "address" },
      { indexed: false, internalType: "bytes32", name: "reason", type: "bytes32" },
    ],
    name: "Cancelled",
    type: "event",
  },
  { inputs: [], name: "PausedError", type: "error" },
  { inputs: [], name: "NotPausedError", type: "error" },
  { inputs: [], name: "CancelledError", type: "error" },
  { inputs: [], name: "NotCancelledError", type: "error" },
  { inputs: [], name: "CannotCancel", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "token", type: "address" },
      { indexed: false, internalType: "address", name: "to", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "WithdrawalSuccessful",
    type: "event",
  },
  {
    inputs: [{ internalType: "bytes32", name: "message", type: "bytes32" }],
    name: "pauseTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "message", type: "bytes32" }],
    name: "unpauseTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "message", type: "bytes32" }],
    name: "cancelTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "cancelled",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32[]", name: "rewardNames", type: "bytes32[]" },
      {
        components: [...REWARD_TIER_COMPONENTS],
        internalType: "struct AllOrNothing.Reward[]",
        name: "rewards",
        type: "tuple[]",
      },
    ],
    name: "addRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_platformHash", type: "bytes32" },
      { internalType: "address", name: "_infoAddress", type: "address" },
      { internalType: "address", name: "_trustedForwarder", type: "address" },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "claimRefund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "disburseFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getLifetimeRaisedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRaisedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "rewardName", type: "bytes32" }],
    name: "getReward",
    outputs: [
      {
        components: REWARD_TIER_COMPONENTS,
        internalType: "struct AllOrNothing.Reward",
        name: "reward",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPlatformHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRefundedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPlatformFeePercent",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "backer", type: "address" },
      { internalType: "address", name: "pledgeToken", type: "address" },
      { internalType: "uint256", name: "shippingFee", type: "uint256" },
      { internalType: "bytes32[]", name: "rewardNames", type: "bytes32[]" },
    ],
    name: "pledgeForAReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "backer", type: "address" },
      { internalType: "address", name: "pledgeToken", type: "address" },
      { internalType: "uint256", name: "pledgeAmount", type: "uint256" },
    ],
    name: "pledgeWithoutAReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "rewardName", type: "bytes32" }],
    name: "removeReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
