/**
 * Stable preflight issue codes.
 * Format: `OAK-PF-<SCOPE>-<RULE>`
 * Codes are immutable once released.
 */

// ─── COMMON ────────────────────────────────────────────────────────────────────

export const COMMON_ZERO_ADDRESS = "OAK-PF-COMMON-ZERO_ADDRESS";
export const COMMON_ZERO_BYTES32 = "OAK-PF-COMMON-ZERO_BYTES32";
export const COMMON_ARRAY_LENGTH_MISMATCH = "OAK-PF-COMMON-ARRAY_LENGTH_MISMATCH";
export const COMMON_STATE_UNAVAILABLE = "OAK-PF-COMMON-STATE_UNAVAILABLE";
export const COMMON_SENDER_UNAVAILABLE = "OAK-PF-COMMON-SENDER_UNAVAILABLE";
export const COMMON_ERC20_INSUFFICIENT_BALANCE = "OAK-PF-COMMON-ERC20_INSUFFICIENT_BALANCE";
export const COMMON_ERC20_INSUFFICIENT_ALLOWANCE = "OAK-PF-COMMON-ERC20_INSUFFICIENT_ALLOWANCE";
export const COMMON_ADDRESS_NOT_CHECKSUMMED = "OAK-PF-COMMON-ADDRESS_NOT_CHECKSUMMED";

// ─── CAMPAIGN ──────────────────────────────────────────────────────────────────

export const CAMPAIGN_LAUNCH_BUFFER_VIOLATION = "OAK-PF-CAMPAIGN-LAUNCH_BUFFER_VIOLATION";
export const CAMPAIGN_MIN_DURATION_VIOLATION = "OAK-PF-CAMPAIGN-MIN_DURATION_VIOLATION";
export const CAMPAIGN_PLATFORM_NOT_LISTED = "OAK-PF-CAMPAIGN-PLATFORM_NOT_LISTED";
export const CAMPAIGN_INVALID_PLATFORM_DATA_KEY = "OAK-PF-CAMPAIGN-INVALID_PLATFORM_DATA_KEY";
export const CAMPAIGN_ZERO_PLATFORM_DATA_VALUE = "OAK-PF-CAMPAIGN-ZERO_PLATFORM_DATA_VALUE";
export const CAMPAIGN_DUPLICATE_IDENTIFIER = "OAK-PF-CAMPAIGN-DUPLICATE_IDENTIFIER";
export const CAMPAIGN_CURRENCY_NO_TOKENS = "OAK-PF-CAMPAIGN-CURRENCY_NO_TOKENS";
export const CAMPAIGN_PLATFORM_DATA_LENGTH_MISMATCH = "OAK-PF-CAMPAIGN-PLATFORM_DATA_LENGTH_MISMATCH";
export const CAMPAIGN_DUPLICATE_PLATFORM_HASH = "OAK-PF-CAMPAIGN-DUPLICATE_PLATFORM_HASH";
export const CAMPAIGN_DUPLICATE_PLATFORM_DATA_KEY = "OAK-PF-CAMPAIGN-DUPLICATE_PLATFORM_DATA_KEY";
export const CAMPAIGN_ZERO_GOAL_AMOUNT = "OAK-PF-CAMPAIGN-ZERO_GOAL_AMOUNT";

// ─── FACTORY ───────────────────────────────────────────────────────────────────

export const FACTORY_SENDER_NOT_PLATFORM_ADMIN = "OAK-PF-FACTORY-SENDER_NOT_PLATFORM_ADMIN";
export const FACTORY_PLATFORM_NOT_SELECTED = "OAK-PF-FACTORY-PLATFORM_NOT_SELECTED";
export const FACTORY_PLATFORM_ALREADY_APPROVED = "OAK-PF-FACTORY-PLATFORM_ALREADY_APPROVED";

// ─── PAYMENT ───────────────────────────────────────────────────────────────────

export const PAYMENT_ZERO_PAYMENT_ID = "OAK-PF-PAYMENT-ZERO_PAYMENT_ID";
export const PAYMENT_ZERO_BUYER_ID = "OAK-PF-PAYMENT-ZERO_BUYER_ID";
export const PAYMENT_ZERO_ITEM_ID = "OAK-PF-PAYMENT-ZERO_ITEM_ID";
export const PAYMENT_ZERO_TOKEN = "OAK-PF-PAYMENT-ZERO_TOKEN";
export const PAYMENT_ZERO_AMOUNT = "OAK-PF-PAYMENT-ZERO_AMOUNT";
export const PAYMENT_EXPIRED = "OAK-PF-PAYMENT-EXPIRED";
export const PAYMENT_EXPIRATION_TOO_LONG = "OAK-PF-PAYMENT-EXPIRATION_TOO_LONG";
export const PAYMENT_UNACCEPTED_TOKEN = "OAK-PF-PAYMENT-UNACCEPTED_TOKEN";
export const PAYMENT_ZERO_LINE_ITEM_AMOUNT = "OAK-PF-PAYMENT-ZERO_LINE_ITEM_AMOUNT";
export const PAYMENT_DUPLICATE_PAYMENT_ID = "OAK-PF-PAYMENT-DUPLICATE_PAYMENT_ID";
export const PAYMENT_NOT_FOUND = "OAK-PF-PAYMENT-NOT_FOUND";
export const PAYMENT_ALREADY_CONFIRMED = "OAK-PF-PAYMENT-ALREADY_CONFIRMED";
export const PAYMENT_ALREADY_EXPIRED = "OAK-PF-PAYMENT-ALREADY_EXPIRED";
export const PAYMENT_BATCH_TOO_LARGE = "OAK-PF-PAYMENT-BATCH_TOO_LARGE";
export const PAYMENT_ZERO_BUYER_ADDRESS = "OAK-PF-PAYMENT-ZERO_BUYER_ADDRESS";
export const PAYMENT_UNKNOWN_LINE_ITEM_TYPE = "OAK-PF-PAYMENT-UNKNOWN_LINE_ITEM_TYPE";

// ─── AON (AllOrNothing) ────────────────────────────────────────────────────────

export const AON_UNACCEPTED_TOKEN = "OAK-PF-AON-UNACCEPTED_TOKEN";
export const AON_EMPTY_REWARD_NAMES = "OAK-PF-AON-EMPTY_REWARD_NAMES";
export const AON_ZERO_BACKER = "OAK-PF-AON-ZERO_BACKER";
export const AON_ZERO_PLEDGE_AMOUNT = "OAK-PF-AON-ZERO_PLEDGE_AMOUNT";
export const AON_CAMPAIGN_NOT_STARTED = "OAK-PF-AON-CAMPAIGN_NOT_STARTED";
export const AON_CAMPAIGN_ENDED = "OAK-PF-AON-CAMPAIGN_ENDED";
export const AON_UNKNOWN_REWARD = "OAK-PF-AON-UNKNOWN_REWARD";
export const AON_INVALID_FIRST_REWARD_TIER = "OAK-PF-AON-INVALID_FIRST_REWARD_TIER";

// ─── KWR (KeepWhatsRaised) ────────────────────────────────────────────────────

export const KWR_INVALID_LAUNCH_DEADLINE_ORDER = "OAK-PF-KWR-INVALID_LAUNCH_DEADLINE_ORDER";
export const KWR_FEE_ARRAY_MISMATCH = "OAK-PF-KWR-FEE_ARRAY_MISMATCH";
export const KWR_DUPLICATE_FEE_KEY = "OAK-PF-KWR-DUPLICATE_FEE_KEY";
export const KWR_UNSAFE_FEE_SETUP = "OAK-PF-KWR-UNSAFE_FEE_SETUP";
export const KWR_ZERO_PLEDGE_ID = "OAK-PF-KWR-ZERO_PLEDGE_ID";
export const KWR_ZERO_BACKER = "OAK-PF-KWR-ZERO_BACKER";
export const KWR_UNACCEPTED_TOKEN = "OAK-PF-KWR-UNACCEPTED_TOKEN";
export const KWR_EMPTY_REWARD_NAMES = "OAK-PF-KWR-EMPTY_REWARD_NAMES";
export const KWR_ZERO_PLEDGE_AMOUNT = "OAK-PF-KWR-ZERO_PLEDGE_AMOUNT";
export const KWR_CAMPAIGN_NOT_STARTED = "OAK-PF-KWR-CAMPAIGN_NOT_STARTED";
export const KWR_CAMPAIGN_ENDED = "OAK-PF-KWR-CAMPAIGN_ENDED";
export const KWR_UNKNOWN_REWARD = "OAK-PF-KWR-UNKNOWN_REWARD";
export const KWR_INVALID_FIRST_REWARD_TIER = "OAK-PF-KWR-INVALID_FIRST_REWARD_TIER";
export const KWR_ZERO_PLEDGE_AMOUNT_AND_FEE = "OAK-PF-KWR-ZERO_PLEDGE_AMOUNT_AND_FEE";
export const KWR_WITHDRAWAL_ALREADY_APPROVED = "OAK-PF-KWR-WITHDRAWAL_ALREADY_APPROVED";

// ─── REWARD (shared for addRewards on AON + KWR) ─────────────────────────────

export const REWARD_ARRAY_MISMATCH = "OAK-PF-REWARD-ARRAY_MISMATCH";
export const REWARD_ZERO_NAME = "OAK-PF-REWARD-ZERO_NAME";
export const REWARD_ZERO_VALUE = "OAK-PF-REWARD-ZERO_VALUE";
export const REWARD_ITEM_ARRAY_MISMATCH = "OAK-PF-REWARD-ITEM_ARRAY_MISMATCH";
export const REWARD_DUPLICATE_NAME = "OAK-PF-REWARD-DUPLICATE_NAME";
export const REWARD_ALREADY_EXISTS = "OAK-PF-REWARD-ALREADY_EXISTS";
export const REWARD_NOT_FOUND = "OAK-PF-REWARD-NOT_FOUND";

// ─── SETTLEMENT (shared for settlement/withdrawal/refund paths) ──────────────

export const SETTLEMENT_TREASURY_PAUSED = "OAK-PF-SETTLEMENT-TREASURY_PAUSED";
export const SETTLEMENT_CAMPAIGN_STILL_ACTIVE = "OAK-PF-SETTLEMENT-CAMPAIGN_STILL_ACTIVE";
export const SETTLEMENT_WITHDRAWAL_NOT_APPROVED = "OAK-PF-SETTLEMENT-WITHDRAWAL_NOT_APPROVED";
