export const GLOBAL_PARAMS_ABI = [
  { inputs: [], name: "GlobalParamsInvalidInput", type: "error" },
  {
    inputs: [{ internalType: "bytes32", name: "platformBytes", type: "bytes32" }],
    name: "GlobalParamsPlatformAdminNotSet",
    type: "error",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformBytes", type: "bytes32" }],
    name: "GlobalParamsPlatformAlreadyListed",
    type: "error",
  },
  { inputs: [], name: "GlobalParamsPlatformDataAlreadySet", type: "error" },
  { inputs: [], name: "GlobalParamsPlatformDataNotSet", type: "error" },
  { inputs: [], name: "GlobalParamsPlatformDataSlotTaken", type: "error" },
  {
    inputs: [{ internalType: "bytes32", name: "platformBytes", type: "bytes32" }],
    name: "GlobalParamsPlatformFeePercentIsZero",
    type: "error",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformBytes", type: "bytes32" }],
    name: "GlobalParamsPlatformNotListed",
    type: "error",
  },
  { inputs: [], name: "GlobalParamsUnauthorized", type: "error" },
  { inputs: [], name: "GlobalParamsCurrencyTokenLengthMismatch", type: "error" },
  {
    inputs: [{ internalType: "bytes32", name: "currency", type: "bytes32" }],
    name: "GlobalParamsCurrencyHasNoTokens",
    type: "error",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "currency", type: "bytes32" },
      { internalType: "address", name: "token", type: "address" },
    ],
    name: "GlobalParamsTokenNotInCurrency",
    type: "error",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "platformHash", type: "bytes32" },
      { internalType: "bytes32", name: "typeId", type: "bytes32" },
    ],
    name: "GlobalParamsPlatformLineItemTypeNotFound",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
      { indexed: true, internalType: "address", name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "platformBytes", type: "bytes32" },
      { indexed: true, internalType: "address", name: "newAdminAddress", type: "address" },
    ],
    name: "PlatformAdminAddressUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "platformBytes", type: "bytes32" },
      { indexed: true, internalType: "bytes32", name: "platformDataKey", type: "bytes32" },
    ],
    name: "PlatformDataAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "platformBytes", type: "bytes32" },
      { indexed: false, internalType: "bytes32", name: "platformDataKey", type: "bytes32" },
    ],
    name: "PlatformDataRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "bytes32", name: "platformBytes", type: "bytes32" }],
    name: "PlatformDelisted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "platformBytes", type: "bytes32" },
      { indexed: true, internalType: "address", name: "platformAdminAddress", type: "address" },
      { indexed: false, internalType: "uint256", name: "platformFeePercent", type: "uint256" },
    ],
    name: "PlatformEnlisted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "newAdminAddress", type: "address" }],
    name: "ProtocolAdminAddressUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint256", name: "newFeePercent", type: "uint256" }],
    name: "ProtocolFeePercentUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "currency", type: "bytes32" },
      { indexed: true, internalType: "address", name: "token", type: "address" },
    ],
    name: "TokenAddedToCurrency",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "currency", type: "bytes32" },
      { indexed: true, internalType: "address", name: "token", type: "address" },
    ],
    name: "TokenRemovedFromCurrency",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "platformBytes", type: "bytes32" },
      { indexed: true, internalType: "address", name: "platformAdapter", type: "address" },
    ],
    name: "PlatformAdapterSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "platformBytes", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "claimDelay", type: "uint256" },
    ],
    name: "PlatformClaimDelayUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }],
    name: "Unpaused",
    type: "event",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "key", type: "bytes32" },
      { internalType: "bytes32", name: "value", type: "bytes32" },
    ],
    name: "addToRegistry",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "platformBytes", type: "bytes32" },
      { internalType: "bytes32", name: "platformDataKey", type: "bytes32" },
    ],
    name: "addPlatformData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "currency", type: "bytes32" },
      { internalType: "address", name: "token", type: "address" },
    ],
    name: "addTokenToCurrency",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformDataKey", type: "bytes32" }],
    name: "checkIfPlatformDataKeyValid",
    outputs: [{ internalType: "bool", name: "isValid", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformBytes", type: "bytes32" }],
    name: "checkIfPlatformIsListed",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformBytes", type: "bytes32" }],
    name: "delistPlatform",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "platformHash", type: "bytes32" },
      { internalType: "address", name: "platformAdminAddress", type: "address" },
      { internalType: "uint256", name: "platformFeePercent", type: "uint256" },
      { internalType: "address", name: "platformAdapter", type: "address" },
    ],
    name: "enlistPlatform",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "key", type: "bytes32" }],
    name: "getFromRegistry",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getNumberOfListedPlatforms",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformBytes", type: "bytes32" }],
    name: "getPlatformAdminAddress",
    outputs: [{ internalType: "address", name: "account", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformDataKey", type: "bytes32" }],
    name: "getPlatformDataOwner",
    outputs: [{ internalType: "bytes32", name: "platformBytes", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformBytes", type: "bytes32" }],
    name: "getPlatformAdapter",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformBytes", type: "bytes32" }],
    name: "getPlatformClaimDelay",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformBytes", type: "bytes32" }],
    name: "getPlatformFeePercent",
    outputs: [{ internalType: "uint256", name: "platformFeePercent", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "platformHash", type: "bytes32" },
      { internalType: "bytes32", name: "typeId", type: "bytes32" },
    ],
    name: "getPlatformLineItemType",
    outputs: [
      { internalType: "bool", name: "exists", type: "bool" },
      { internalType: "string", name: "label", type: "string" },
      { internalType: "bool", name: "countsTowardGoal", type: "bool" },
      { internalType: "bool", name: "applyProtocolFee", type: "bool" },
      { internalType: "bool", name: "canRefund", type: "bool" },
      { internalType: "bool", name: "instantTransfer", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "protocolAdminAddress", type: "address" },
      { internalType: "uint256", name: "protocolFeePercent", type: "uint256" },
      { internalType: "bytes32[]", name: "currencies", type: "bytes32[]" },
      { internalType: "address[][]", name: "tokensPerCurrency", type: "address[][]" },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getProtocolAdminAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getProtocolFeePercent",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "currency", type: "bytes32" }],
    name: "getTokensForCurrency",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "platformBytes", type: "bytes32" },
      { internalType: "bytes32", name: "platformDataKey", type: "bytes32" },
    ],
    name: "removePlatformData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "platformHash", type: "bytes32" },
      { internalType: "bytes32", name: "typeId", type: "bytes32" },
    ],
    name: "removePlatformLineItemType",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "currency", type: "bytes32" },
      { internalType: "address", name: "token", type: "address" },
    ],
    name: "removeTokenFromCurrency",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "platformBytes", type: "bytes32" },
      { internalType: "address", name: "platformAdapter", type: "address" },
    ],
    name: "setPlatformAdapter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "platformHash", type: "bytes32" },
      { internalType: "bytes32", name: "typeId", type: "bytes32" },
      { internalType: "string", name: "label", type: "string" },
      { internalType: "bool", name: "countsTowardGoal", type: "bool" },
      { internalType: "bool", name: "applyProtocolFee", type: "bool" },
      { internalType: "bool", name: "canRefund", type: "bool" },
      { internalType: "bool", name: "instantTransfer", type: "bool" },
    ],
    name: "setPlatformLineItemType",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "platformBytes", type: "bytes32" },
      { internalType: "address", name: "platformAdminAddress", type: "address" },
    ],
    name: "updatePlatformAdminAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "platformBytes", type: "bytes32" },
      { internalType: "uint256", name: "claimDelay", type: "uint256" },
    ],
    name: "updatePlatformClaimDelay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "protocolAdminAddress", type: "address" }],
    name: "updateProtocolAdminAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "protocolFeePercent", type: "uint256" }],
    name: "updateProtocolFeePercent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export type GlobalParamsAbi = typeof GLOBAL_PARAMS_ABI;
