/** PaymentTreasury ABI — typed const, co-located with the contract that uses it. Shared interface for PaymentTreasury and TimeConstrainedPaymentTreasury. */
const PAYMENT_LINE_ITEM_COMPONENTS = [
  { internalType: "bytes32", name: "typeId", type: "bytes32" },
  { internalType: "uint256", name: "amount", type: "uint256" },
  { internalType: "string", name: "label", type: "string" },
  { internalType: "bool", name: "countsTowardGoal", type: "bool" },
  { internalType: "bool", name: "applyProtocolFee", type: "bool" },
  { internalType: "bool", name: "canRefund", type: "bool" },
  { internalType: "bool", name: "instantTransfer", type: "bool" },
] as const;

const LINE_ITEM_COMPONENTS = [
  { internalType: "bytes32", name: "typeId", type: "bytes32" },
  { internalType: "uint256", name: "amount", type: "uint256" },
] as const;

const EXTERNAL_FEES_COMPONENTS = [
  { internalType: "bytes32", name: "feeType", type: "bytes32" },
  { internalType: "uint256", name: "feeAmount", type: "uint256" },
] as const;

export const PAYMENT_TREASURY_ABI = [
  { inputs: [], name: "PaymentTreasuryUnAuthorized", type: "error" },
  { inputs: [], name: "PaymentTreasuryInvalidInput", type: "error" },
  {
    inputs: [{ internalType: "bytes32", name: "paymentId", type: "bytes32" }],
    name: "PaymentTreasuryPaymentAlreadyExist",
    type: "error",
  },
  {
    inputs: [{ internalType: "bytes32", name: "paymentId", type: "bytes32" }],
    name: "PaymentTreasuryPaymentAlreadyConfirmed",
    type: "error",
  },
  {
    inputs: [{ internalType: "bytes32", name: "paymentId", type: "bytes32" }],
    name: "PaymentTreasuryPaymentAlreadyExpired",
    type: "error",
  },
  {
    inputs: [{ internalType: "bytes32", name: "paymentId", type: "bytes32" }],
    name: "PaymentTreasuryPaymentNotExist",
    type: "error",
  },
  { inputs: [], name: "PaymentTreasuryCampaignInfoIsPaused", type: "error" },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "PaymentTreasuryTokenNotAccepted",
    type: "error",
  },
  { inputs: [], name: "PaymentTreasurySuccessConditionNotFulfilled", type: "error" },
  { inputs: [], name: "PaymentTreasuryFeeNotDisbursed", type: "error" },
  {
    inputs: [{ internalType: "bytes32", name: "paymentId", type: "bytes32" }],
    name: "PaymentTreasuryPaymentNotConfirmed",
    type: "error",
  },
  {
    inputs: [{ internalType: "bytes32", name: "paymentId", type: "bytes32" }],
    name: "PaymentTreasuryPaymentNotClaimable",
    type: "error",
  },
  { inputs: [], name: "PaymentTreasuryAlreadyWithdrawn", type: "error" },
  {
    inputs: [{ internalType: "bytes32", name: "paymentId", type: "bytes32" }],
    name: "PaymentTreasuryCryptoPayment",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "withdrawalAmount", type: "uint256" },
      { internalType: "uint256", name: "fee", type: "uint256" },
    ],
    name: "PaymentTreasuryInsufficientFundsForFee",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "required", type: "uint256" },
      { internalType: "uint256", name: "available", type: "uint256" },
    ],
    name: "PaymentTreasuryInsufficientBalance",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "expiration", type: "uint256" },
      { internalType: "uint256", name: "maxExpiration", type: "uint256" },
    ],
    name: "PaymentTreasuryExpirationExceedsMax",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint256", name: "claimableAt", type: "uint256" }],
    name: "PaymentTreasuryClaimWindowNotReached",
    type: "error",
  },
  { inputs: [], name: "PaymentTreasuryNoFundsToClaim", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "address", name: "buyerAddress", type: "address" },
      { indexed: true, internalType: "bytes32", name: "paymentId", type: "bytes32" },
      { indexed: false, internalType: "bytes32", name: "buyerId", type: "bytes32" },
      { indexed: true, internalType: "bytes32", name: "itemId", type: "bytes32" },
      { indexed: true, internalType: "address", name: "paymentToken", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "expiration", type: "uint256" },
      { indexed: false, internalType: "bool", name: "isCryptoPayment", type: "bool" },
    ],
    name: "PaymentCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "bytes32", name: "paymentId", type: "bytes32" }],
    name: "PaymentCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "bytes32", name: "paymentId", type: "bytes32" }],
    name: "PaymentConfirmed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "bytes32[]", name: "paymentIds", type: "bytes32[]" }],
    name: "PaymentBatchConfirmed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "bytes32[]", name: "paymentIds", type: "bytes32[]" }],
    name: "PaymentBatchCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "token", type: "address" },
      { indexed: false, internalType: "uint256", name: "protocolShare", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "platformShare", type: "uint256" },
    ],
    name: "FeesDisbursed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "token", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "fee", type: "uint256" },
    ],
    name: "WithdrawalWithFeeSuccessful",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "paymentId", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "refundAmount", type: "uint256" },
      { indexed: true, internalType: "address", name: "claimer", type: "address" },
    ],
    name: "RefundClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "token", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: true, internalType: "address", name: "platformAdmin", type: "address" },
    ],
    name: "NonGoalLineItemsClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "token", type: "address" },
      { indexed: false, internalType: "uint256", name: "platformAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "protocolAmount", type: "uint256" },
    ],
    name: "ExpiredFundsClaimed",
    type: "event",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_platformHash", type: "bytes32" },
      { internalType: "address", name: "_infoAddress", type: "address" },
      { internalType: "address", name: "_trustedForwarder", type: "address" },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getplatformHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getplatformFeePercent",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRaisedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAvailableRaisedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "paymentId", type: "bytes32" }],
    name: "getPaymentData",
    outputs: [
      {
        components: [
          { internalType: "address", name: "buyerAddress", type: "address" },
          { internalType: "bytes32", name: "buyerId", type: "bytes32" },
          { internalType: "bytes32", name: "itemId", type: "bytes32" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "uint256", name: "expiration", type: "uint256" },
          { internalType: "bool", name: "isConfirmed", type: "bool" },
          { internalType: "bool", name: "isCryptoPayment", type: "bool" },
          { internalType: "uint256", name: "lineItemCount", type: "uint256" },
          { internalType: "address", name: "paymentToken", type: "address" },
          {
            components: [...PAYMENT_LINE_ITEM_COMPONENTS],
            internalType: "struct ICampaignPaymentTreasury.PaymentLineItem[]",
            name: "lineItems",
            type: "tuple[]",
          },
          {
            components: [...EXTERNAL_FEES_COMPONENTS],
            internalType: "struct ICampaignPaymentTreasury.ExternalFees[]",
            name: "externalFees",
            type: "tuple[]",
          },
        ],
        internalType: "struct ICampaignPaymentTreasury.PaymentData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getLifetimeRaisedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRefundedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getExpectedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "cancelled",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "paymentId", type: "bytes32" },
      { internalType: "bytes32", name: "buyerId", type: "bytes32" },
      { internalType: "bytes32", name: "itemId", type: "bytes32" },
      { internalType: "address", name: "paymentToken", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "expiration", type: "uint256" },
      {
        components: [...LINE_ITEM_COMPONENTS],
        internalType: "struct ICampaignPaymentTreasury.LineItem[]",
        name: "lineItems",
        type: "tuple[]",
      },
      {
        components: [...EXTERNAL_FEES_COMPONENTS],
        internalType: "struct ICampaignPaymentTreasury.ExternalFees[]",
        name: "externalFees",
        type: "tuple[]",
      },
    ],
    name: "createPayment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32[]", name: "paymentIds", type: "bytes32[]" },
      { internalType: "bytes32[]", name: "buyerIds", type: "bytes32[]" },
      { internalType: "bytes32[]", name: "itemIds", type: "bytes32[]" },
      { internalType: "address[]", name: "paymentTokens", type: "address[]" },
      { internalType: "uint256[]", name: "amounts", type: "uint256[]" },
      { internalType: "uint256[]", name: "expirations", type: "uint256[]" },
      {
        components: [...LINE_ITEM_COMPONENTS],
        internalType: "struct ICampaignPaymentTreasury.LineItem[][]",
        name: "lineItemsArray",
        type: "tuple[][]",
      },
      {
        components: [...EXTERNAL_FEES_COMPONENTS],
        internalType: "struct ICampaignPaymentTreasury.ExternalFees[][]",
        name: "externalFeesArray",
        type: "tuple[][]",
      },
    ],
    name: "createPaymentBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "paymentId", type: "bytes32" },
      { internalType: "bytes32", name: "itemId", type: "bytes32" },
      { internalType: "address", name: "buyerAddress", type: "address" },
      { internalType: "address", name: "paymentToken", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      {
        components: [...LINE_ITEM_COMPONENTS],
        internalType: "struct ICampaignPaymentTreasury.LineItem[]",
        name: "lineItems",
        type: "tuple[]",
      },
      {
        components: [...EXTERNAL_FEES_COMPONENTS],
        internalType: "struct ICampaignPaymentTreasury.ExternalFees[]",
        name: "externalFees",
        type: "tuple[]",
      },
    ],
    name: "processCryptoPayment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "paymentId", type: "bytes32" }],
    name: "cancelPayment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "paymentId", type: "bytes32" },
      { internalType: "address", name: "buyerAddress", type: "address" },
    ],
    name: "confirmPayment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32[]", name: "paymentIds", type: "bytes32[]" },
      { internalType: "address[]", name: "buyerAddresses", type: "address[]" },
    ],
    name: "confirmPaymentBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "disburseFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "paymentId", type: "bytes32" },
      { internalType: "address", name: "refundAddress", type: "address" },
    ],
    name: "claimRefund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "paymentId", type: "bytes32" }],
    name: "claimRefund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "claimExpiredFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "claimNonGoalLineItems",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "message", type: "bytes32" }],
    name: "pauseTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "message", type: "bytes32" }],
    name: "unpauseTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "address", name: "account", type: "address" },
      { indexed: false, internalType: "bytes32", name: "message", type: "bytes32" },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "address", name: "account", type: "address" },
      { indexed: false, internalType: "bytes32", name: "message", type: "bytes32" },
    ],
    name: "Unpaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "account", type: "address" },
      { indexed: false, internalType: "bytes32", name: "reason", type: "bytes32" },
    ],
    name: "Cancelled",
    type: "event",
  },
  { inputs: [], name: "PausedError", type: "error" },
  { inputs: [], name: "NotPausedError", type: "error" },
  { inputs: [], name: "CancelledError", type: "error" },
  { inputs: [], name: "NotCancelledError", type: "error" },
  { inputs: [], name: "CannotCancel", type: "error" },
  {
    inputs: [],
    name: "paused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "message", type: "bytes32" }],
    name: "cancelTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
