const CAMPAIGN_DATA_COMPONENTS = [
  { internalType: "uint256", name: "launchTime", type: "uint256" },
  { internalType: "uint256", name: "deadline", type: "uint256" },
  { internalType: "uint256", name: "goalAmount", type: "uint256" },
  { internalType: "bytes32", name: "currency", type: "bytes32" },
] as const;

export const CAMPAIGN_INFO_ABI = [
  { inputs: [], name: "AdminAccessCheckerUnauthorized", type: "error" },
  { inputs: [], name: "CampaignInfoInvalidInput", type: "error" },
  {
    inputs: [
      { internalType: "bytes32", name: "platformBytes", type: "bytes32" },
      { internalType: "bool", name: "selection", type: "bool" },
    ],
    name: "CampaignInfoInvalidPlatformUpdate",
    type: "error",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformBytes", type: "bytes32" }],
    name: "CampaignInfoPlatformNotSelected",
    type: "error",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformHash", type: "bytes32" }],
    name: "CampaignInfoPlatformAlreadyApproved",
    type: "error",
  },
  { inputs: [], name: "CampaignInfoUnauthorized", type: "error" },
  { inputs: [], name: "CampaignInfoIsLocked", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "inputTime", type: "uint256" },
      { internalType: "uint256", name: "currentTime", type: "uint256" },
    ],
    name: "CurrentTimeIsGreater",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "inputTime", type: "uint256" },
      { internalType: "uint256", name: "currentTime", type: "uint256" },
    ],
    name: "CurrentTimeIsLess",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "initialTime", type: "uint256" },
      { internalType: "uint256", name: "finalTime", type: "uint256" },
    ],
    name: "CurrentTimeIsNotWithinRange",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint256", name: "newDeadline", type: "uint256" }],
    name: "CampaignInfoDeadlineUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint256", name: "newGoalAmount", type: "uint256" }],
    name: "CampaignInfoGoalAmountUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint256", name: "newLaunchTime", type: "uint256" }],
    name: "CampaignInfoLaunchTimeUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "platformBytes", type: "bytes32" },
      { indexed: true, internalType: "address", name: "platformTreasury", type: "address" },
    ],
    name: "CampaignInfoPlatformInfoUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "platformBytes", type: "bytes32" },
      { indexed: false, internalType: "bool", name: "selection", type: "bool" },
    ],
    name: "CampaignInfoSelectedPlatformUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
      { indexed: true, internalType: "address", name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "address", name: "account", type: "address" },
      { indexed: false, internalType: "bytes32", name: "message", type: "bytes32" },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "address", name: "account", type: "address" },
      { indexed: false, internalType: "bytes32", name: "message", type: "bytes32" },
    ],
    name: "Unpaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "account", type: "address" },
      { indexed: false, internalType: "bytes32", name: "reason", type: "bytes32" },
    ],
    name: "Cancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "tokenId", type: "uint256" },
      { indexed: true, internalType: "address", name: "backer", type: "address" },
      { indexed: true, internalType: "address", name: "treasury", type: "address" },
      { indexed: false, internalType: "bytes32", name: "reward", type: "bytes32" },
    ],
    name: "PledgeNFTMinted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "string", name: "newImageURI", type: "string" }],
    name: "ImageURIUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "string", name: "newContractURI", type: "string" }],
    name: "ContractURIUpdated",
    type: "event",
  },
  { inputs: [], name: "PausedError", type: "error" },
  { inputs: [], name: "NotPausedError", type: "error" },
  { inputs: [], name: "CancelledError", type: "error" },
  { inputs: [], name: "NotCancelledError", type: "error" },
  { inputs: [], name: "CannotCancel", type: "error" },
  { inputs: [], name: "PledgeNFTUnAuthorized", type: "error" },
  { inputs: [], name: "PledgeNFTInvalidJsonString", type: "error" },
  {
    inputs: [],
    name: "getPledgeCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "getPledgeData",
    outputs: [
      {
        components: [
          { internalType: "address", name: "backer", type: "address" },
          { internalType: "bytes32", name: "reward", type: "bytes32" },
          { internalType: "address", name: "treasury", type: "address" },
          { internalType: "address", name: "tokenAddress", type: "address" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "uint256", name: "shippingFee", type: "uint256" },
          { internalType: "uint256", name: "tipAmount", type: "uint256" },
        ],
        internalType: "struct PledgeNFT.PledgeData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getImageURI",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "contractURI",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "tokenURI",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "ownerOf",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "message", type: "bytes32" }],
    name: "_cancelCampaign",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "message", type: "bytes32" }],
    name: "_pauseCampaign",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "platformBytes", type: "bytes32" },
      { internalType: "address", name: "platformTreasuryAddress", type: "address" },
    ],
    name: "_setPlatformInfo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "message", type: "bytes32" }],
    name: "_unpauseCampaign",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformBytes", type: "bytes32" }],
    name: "checkIfPlatformSelected",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getDeadline",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getGoalAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getIdentifierHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getLaunchTime",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformBytes", type: "bytes32" }],
    name: "getPlatformAdminAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformDataKey", type: "bytes32" }],
    name: "getPlatformData",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformBytes", type: "bytes32" }],
    name: "getPlatformFeePercent",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getProtocolAdminAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getProtocolFeePercent",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCampaignCurrency",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAcceptedTokens",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "isTokenAccepted",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformHash", type: "bytes32" }],
    name: "getPlatformClaimDelay",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalRaisedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalLifetimeRaisedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalRefundedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalAvailableRaisedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalCancelledAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalExpectedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "key", type: "bytes32" }],
    name: "getDataFromRegistry",
    outputs: [{ internalType: "bytes32", name: "value", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getBufferTime",
    outputs: [{ internalType: "uint256", name: "bufferTime", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "platformHash", type: "bytes32" },
      { internalType: "bytes32", name: "typeId", type: "bytes32" },
    ],
    name: "getLineItemType",
    outputs: [
      { internalType: "bool", name: "exists", type: "bool" },
      { internalType: "string", name: "label", type: "string" },
      { internalType: "bool", name: "countsTowardGoal", type: "bool" },
      { internalType: "bool", name: "applyProtocolFee", type: "bool" },
      { internalType: "bool", name: "canRefund", type: "bool" },
      { internalType: "bool", name: "instantTransfer", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCampaignConfig",
    outputs: [
      {
        components: [
          { internalType: "address", name: "treasuryFactory", type: "address" },
          { internalType: "uint256", name: "protocolFeePercent", type: "uint256" },
          { internalType: "bytes32", name: "identifierHash", type: "bytes32" },
        ],
        internalType: "struct CampaignInfo.Config",
        name: "config",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getApprovedPlatformHashes",
    outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isLocked",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "platformHash", type: "bytes32" }],
    name: "checkIfPlatformApproved",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "cancelled",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "creator", type: "address" },
      { internalType: "contract IGlobalParams", name: "globalParams", type: "address" },
      { internalType: "bytes32[]", name: "selectedPlatformHash", type: "bytes32[]" },
      { internalType: "bytes32[]", name: "platformDataKey", type: "bytes32[]" },
      { internalType: "bytes32[]", name: "platformDataValue", type: "bytes32[]" },
      {
        components: [...CAMPAIGN_DATA_COMPONENTS],
        internalType: "struct ICampaignData.CampaignData",
        name: "campaignData",
        type: "tuple",
      },
      { internalType: "address[]", name: "acceptedTokens", type: "address[]" },
      { internalType: "string", name: "nftName", type: "string" },
      { internalType: "string", name: "nftSymbol", type: "string" },
      { internalType: "string", name: "nftImageURI", type: "string" },
      { internalType: "string", name: "nftContractURI", type: "string" },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "backer", type: "address" },
      { internalType: "bytes32", name: "reward", type: "bytes32" },
      { internalType: "address", name: "tokenAddress", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "shippingFee", type: "uint256" },
      { internalType: "uint256", name: "tipAmount", type: "uint256" },
    ],
    name: "mintNFTForPledge",
    outputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "newImageURI", type: "string" }],
    name: "setImageURI",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "newContractURI", type: "string" }],
    name: "updateContractURI",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "account", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "deadline", type: "uint256" }],
    name: "updateDeadline",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "goalAmount", type: "uint256" }],
    name: "updateGoalAmount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "launchTime", type: "uint256" }],
    name: "updateLaunchTime",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "platformHash", type: "bytes32" },
      { internalType: "bool", name: "selection", type: "bool" },
      { internalType: "bytes32[]", name: "platformDataKey", type: "bytes32[]" },
      { internalType: "bytes32[]", name: "platformDataValue", type: "bytes32[]" },
    ],
    name: "updateSelectedPlatform",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
