const CAMPAIGN_DATA_COMPONENTS = [
  { internalType: "uint256", name: "launchTime", type: "uint256" },
  { internalType: "uint256", name: "deadline", type: "uint256" },
  { internalType: "uint256", name: "goalAmount", type: "uint256" },
  { internalType: "bytes32", name: "currency", type: "bytes32" },
] as const;

export const CAMPAIGN_INFO_FACTORY_ABI = [
  { inputs: [], name: "CampaignInfoFactoryInvalidInput", type: "error" },
  { inputs: [], name: "CampaignInfoFactoryCampaignInitializationFailed", type: "error" },
  {
    inputs: [{ internalType: "bytes32", name: "platformHash", type: "bytes32" }],
    name: "CampaignInfoFactoryPlatformNotListed",
    type: "error",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "identifierHash", type: "bytes32" },
      { internalType: "address", name: "cloneExists", type: "address" },
    ],
    name: "CampaignInfoFactoryCampaignWithSameIdentifierExists",
    type: "error",
  },
  { inputs: [], name: "CampaignInfoInvalidTokenList", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "identifierHash", type: "bytes32" },
      { indexed: true, internalType: "address", name: "campaignInfoAddress", type: "address" },
    ],
    name: "CampaignInfoFactoryCampaignCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "CampaignInfoFactoryCampaignInitialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
      { indexed: true, internalType: "address", name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "creator", type: "address" },
      { internalType: "bytes32", name: "identifierHash", type: "bytes32" },
      { internalType: "bytes32[]", name: "selectedPlatformHash", type: "bytes32[]" },
      { internalType: "bytes32[]", name: "platformDataKey", type: "bytes32[]" },
      { internalType: "bytes32[]", name: "platformDataValue", type: "bytes32[]" },
      {
        components: [...CAMPAIGN_DATA_COMPONENTS],
        internalType: "struct ICampaignData.CampaignData",
        name: "campaignData",
        type: "tuple",
      },
      { internalType: "string", name: "nftName", type: "string" },
      { internalType: "string", name: "nftSymbol", type: "string" },
      { internalType: "string", name: "nftImageURI", type: "string" },
      { internalType: "string", name: "contractURI", type: "string" },
    ],
    name: "createCampaign",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "identifierHash", type: "bytes32" }],
    name: "identifierToCampaignInfo",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "initialOwner", type: "address" },
      { internalType: "contract IGlobalParams", name: "globalParams", type: "address" },
      { internalType: "address", name: "campaignImplementation", type: "address" },
      { internalType: "address", name: "treasuryFactoryAddress", type: "address" },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "campaignInfo", type: "address" }],
    name: "isValidCampaignInfo",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newImplementation", type: "address" }],
    name: "updateImplementation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
