/**
 * KeepWhatsRaised treasury ABI — pledgeId-based pledges and withdraw(token, amount).
 * Matches the provided KeepWhatsRaised contract (no Fiat; different signatures from AllOrNothing).
 */
const REWARD_TIER_COMPONENTS = [
  { internalType: "uint256", name: "rewardValue", type: "uint256" },
  { internalType: "bool", name: "isRewardTier", type: "bool" },
  { internalType: "bytes32[]", name: "itemId", type: "bytes32[]" },
  { internalType: "uint256[]", name: "itemValue", type: "uint256[]" },
  { internalType: "uint256[]", name: "itemQuantity", type: "uint256[]" },
] as const;

const CONFIG_COMPONENTS = [
  { internalType: "uint256", name: "minimumWithdrawalForFeeExemption", type: "uint256" },
  { internalType: "uint256", name: "withdrawalDelay", type: "uint256" },
  { internalType: "uint256", name: "refundDelay", type: "uint256" },
  { internalType: "uint256", name: "configLockPeriod", type: "uint256" },
  { internalType: "bool", name: "isColombianCreator", type: "bool" },
] as const;

const FEE_KEYS_COMPONENTS = [
  { internalType: "bytes32", name: "flatFeeKey", type: "bytes32" },
  { internalType: "bytes32", name: "cumulativeFlatFeeKey", type: "bytes32" },
  { internalType: "bytes32[]", name: "grossPercentageFeeKeys", type: "bytes32[]" },
] as const;

const FEE_VALUES_COMPONENTS = [
  { internalType: "uint256", name: "flatFeeValue", type: "uint256" },
  { internalType: "uint256", name: "cumulativeFlatFeeValue", type: "uint256" },
  { internalType: "uint256[]", name: "grossPercentageFeeValues", type: "uint256[]" },
] as const;

const CAMPAIGN_DATA_COMPONENTS = [
  { internalType: "uint256", name: "launchTime", type: "uint256" },
  { internalType: "uint256", name: "deadline", type: "uint256" },
  { internalType: "uint256", name: "goalAmount", type: "uint256" },
  { internalType: "bytes32", name: "currency", type: "bytes32" },
] as const;

export const KEEP_WHATS_RAISED_ABI = [
  { inputs: [], name: "AccessCheckerUnauthorized", type: "error" },
  { inputs: [], name: "KeepWhatsRaisedUnAuthorized", type: "error" },
  { inputs: [], name: "KeepWhatsRaisedInvalidInput", type: "error" },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "KeepWhatsRaisedTokenNotAccepted",
    type: "error",
  },
  { inputs: [], name: "KeepWhatsRaisedRewardExists", type: "error" },
  { inputs: [], name: "KeepWhatsRaisedDisabled", type: "error" },
  { inputs: [], name: "KeepWhatsRaisedAlreadyEnabled", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "availableAmount", type: "uint256" },
      { internalType: "uint256", name: "withdrawalAmount", type: "uint256" },
      { internalType: "uint256", name: "fee", type: "uint256" },
    ],
    name: "KeepWhatsRaisedInsufficientFundsForWithdrawalAndFee",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "withdrawalAmount", type: "uint256" },
      { internalType: "uint256", name: "fee", type: "uint256" },
    ],
    name: "KeepWhatsRaisedInsufficientFundsForFee",
    type: "error",
  },
  { inputs: [], name: "KeepWhatsRaisedAlreadyWithdrawn", type: "error" },
  { inputs: [], name: "KeepWhatsRaisedAlreadyClaimed", type: "error" },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "KeepWhatsRaisedNotClaimable",
    type: "error",
  },
  { inputs: [], name: "KeepWhatsRaisedNotClaimableAdmin", type: "error" },
  { inputs: [], name: "KeepWhatsRaisedConfigLocked", type: "error" },
  { inputs: [], name: "KeepWhatsRaisedDisbursementBlocked", type: "error" },
  {
    inputs: [{ internalType: "bytes32", name: "pledgeId", type: "bytes32" }],
    name: "KeepWhatsRaisedPledgeAlreadyProcessed",
    type: "error",
  },
  { inputs: [], name: "TreasuryCampaignInfoIsPaused", type: "error" },
  { inputs: [], name: "TreasuryFeeNotDisbursed", type: "error" },
  { inputs: [], name: "TreasuryTransferFailed", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: true, internalType: "address", name: "approved", type: "address" },
      { indexed: true, internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: true, internalType: "address", name: "operator", type: "address" },
      { indexed: false, internalType: "bool", name: "approved", type: "bool" },
    ],
    name: "ApprovalForAll",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "token", type: "address" },
      { indexed: false, internalType: "uint256", name: "protocolShare", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "platformShare", type: "uint256" },
    ],
    name: "FeesDisbursed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "address", name: "account", type: "address" },
      { indexed: false, internalType: "bytes32", name: "message", type: "bytes32" },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "backer", type: "address" },
      { indexed: true, internalType: "address", name: "pledgeToken", type: "address" },
      { indexed: false, internalType: "bytes32", name: "reward", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "pledgeAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "tip", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "tokenId", type: "uint256" },
      { indexed: false, internalType: "bytes32[]", name: "rewards", type: "bytes32[]" },
    ],
    name: "Receipt",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bytes32[]", name: "rewardNames", type: "bytes32[]" },
      {
        components: [...REWARD_TIER_COMPONENTS],
        indexed: false,
        internalType: "struct IReward.Reward[]",
        name: "rewards",
        type: "tuple[]",
      },
    ],
    name: "RewardsAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "bytes32", name: "rewardName", type: "bytes32" }],
    name: "RewardRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "WithdrawalApproved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [...CONFIG_COMPONENTS],
        indexed: false,
        internalType: "struct KeepWhatsRaised.Config",
        name: "config",
        type: "tuple",
      },
      {
        components: [...CAMPAIGN_DATA_COMPONENTS],
        indexed: false,
        internalType: "struct ICampaignData.CampaignData",
        name: "campaignData",
        type: "tuple",
      },
      {
        components: [...FEE_KEYS_COMPONENTS],
        indexed: false,
        internalType: "struct KeepWhatsRaised.FeeKeys",
        name: "feeKeys",
        type: "tuple",
      },
      {
        components: [...FEE_VALUES_COMPONENTS],
        indexed: false,
        internalType: "struct KeepWhatsRaised.FeeValues",
        name: "feeValues",
        type: "tuple",
      },
    ],
    name: "TreasuryConfigured",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: true, internalType: "address", name: "claimer", type: "address" },
    ],
    name: "TipClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: true, internalType: "address", name: "claimer", type: "address" },
    ],
    name: "FundClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "tokenId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "refundAmount", type: "uint256" },
      { indexed: true, internalType: "address", name: "claimer", type: "address" },
    ],
    name: "RefundClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint256", name: "newDeadline", type: "uint256" }],
    name: "KeepWhatsRaisedDeadlineUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "uint256", name: "newGoalAmount", type: "uint256" }],
    name: "KeepWhatsRaisedGoalAmountUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "pledgeId", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "fee", type: "uint256" },
    ],
    name: "KeepWhatsRaisedPaymentGatewayFeeSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "to", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "fee", type: "uint256" },
    ],
    name: "WithdrawalWithFeeSuccessful",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      { indexed: true, internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "address", name: "account", type: "address" },
      { indexed: false, internalType: "bytes32", name: "message", type: "bytes32" },
    ],
    name: "Unpaused",
    type: "event",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_platformHash", type: "bytes32" },
      { internalType: "address", name: "_infoAddress", type: "address" },
      { internalType: "address", name: "_trustedForwarder", type: "address" },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "message", type: "bytes32" }],
    name: "pauseTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "message", type: "bytes32" }],
    name: "unpauseTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "message", type: "bytes32" }],
    name: "cancelTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "cancelled",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32[]", name: "rewardNames", type: "bytes32[]" },
      {
        components: [...REWARD_TIER_COMPONENTS],
        internalType: "struct KeepWhatsRaised.Reward[]",
        name: "rewards",
        type: "tuple[]",
      },
    ],
    name: "addRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "approve",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "claimRefund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "disburseFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "getApproved",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAvailableRaisedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getWithdrawalApprovalStatus",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getLaunchTime",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getDeadline",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getGoalAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "pledgeId", type: "bytes32" }],
    name: "getPaymentGatewayFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "feeKey", type: "bytes32" }],
    name: "getFeeValue",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "pledgeId", type: "bytes32" },
      { internalType: "uint256", name: "fee", type: "uint256" },
    ],
    name: "setPaymentGatewayFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "approveWithdrawal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [...CONFIG_COMPONENTS],
        internalType: "struct KeepWhatsRaised.Config",
        name: "config",
        type: "tuple",
      },
      {
        components: [...CAMPAIGN_DATA_COMPONENTS],
        internalType: "struct ICampaignData.CampaignData",
        name: "campaignData",
        type: "tuple",
      },
      {
        components: [...FEE_KEYS_COMPONENTS],
        internalType: "struct KeepWhatsRaised.FeeKeys",
        name: "feeKeys",
        type: "tuple",
      },
      {
        components: [...FEE_VALUES_COMPONENTS],
        internalType: "struct KeepWhatsRaised.FeeValues",
        name: "feeValues",
        type: "tuple",
      },
    ],
    name: "configureTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "deadline", type: "uint256" }],
    name: "updateDeadline",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "goalAmount", type: "uint256" }],
    name: "updateGoalAmount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "pledgeId", type: "bytes32" },
      { internalType: "address", name: "backer", type: "address" },
      { internalType: "address", name: "pledgeToken", type: "address" },
      { internalType: "uint256", name: "pledgeAmount", type: "uint256" },
      { internalType: "uint256", name: "tip", type: "uint256" },
      { internalType: "uint256", name: "fee", type: "uint256" },
      { internalType: "bytes32[]", name: "reward", type: "bytes32[]" },
      { internalType: "bool", name: "isPledgeForAReward", type: "bool" },
    ],
    name: "setFeeAndPledge",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "claimTip",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "claimFund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getLifetimeRaisedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRaisedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "rewardName", type: "bytes32" }],
    name: "getReward",
    outputs: [
      {
        components: REWARD_TIER_COMPONENTS,
        internalType: "struct KeepWhatsRaised.Reward",
        name: "reward",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPlatformHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRefundedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPlatformFeePercent",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "operator", type: "address" },
    ],
    name: "isApprovedForAll",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "ownerOf",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "pledgeId", type: "bytes32" },
      { internalType: "address", name: "backer", type: "address" },
      { internalType: "address", name: "pledgeToken", type: "address" },
      { internalType: "uint256", name: "tip", type: "uint256" },
      { internalType: "bytes32[]", name: "rewardNames", type: "bytes32[]" },
    ],
    name: "pledgeForAReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "pledgeId", type: "bytes32" },
      { internalType: "address", name: "backer", type: "address" },
      { internalType: "address", name: "pledgeToken", type: "address" },
      { internalType: "uint256", name: "pledgeAmount", type: "uint256" },
      { internalType: "uint256", name: "tip", type: "uint256" },
    ],
    name: "pledgeWithoutAReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "rewardName", type: "bytes32" }],
    name: "removeReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      { internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "operator", type: "address" },
      { internalType: "bool", name: "approved", type: "bool" },
    ],
    name: "setApprovalForAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "tokenURI",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "token", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
